name: Model verification example for the CruiseControlMode model

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    paths:
      - 'Test/Sample/ctrl/ctrldesign/parts/SamplePartsA/**/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MODELNAME: SamplePartsA
  MODELPATH: C:\Users\C9166\actions-runner\_work\TestEnv\TestEnv\Test\Sample\ctrl\ctrldesign\parts\SamplePartsA

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
  setup:
    runs-on: self-hosted
    steps:
      - name: Model Setup
        shell: cmd
        run: |
          matlab -batch "addpath('C:\Users\C9166\actions-runner\_work\TestEnv\TestEnv\tool'); trse_ci_mdlenv('${{ env.MODELPATH }}','${{ env.MODELNAME }}');"
          
  mdlchk:
    runs-on: self-hosted
    needs: [setup]
    steps:
      - name: Run ModelAdvisor
        shell: cmd
        run: |
          matlab -batch "trse_ci_mdlchk('${{ env.MODELPATH }}','${{ env.MODELNAME }}');"